# Generated by Django 3.0.6 on 2020-05-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacloned', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
    ]
