# Generated by Django 3.0.6 on 2020-05-30 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacloned', '0003_auto_20200531_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.CharField(max_length=300),
        ),
    ]
